# Base Config
base.url=https://automationexercise.com
browser=chrome
username=testuser@gmail.com
password=12345

# API Endpoints
endpoint.products=/api/productsList
endpoint.search=/api/searchProduct
endpoint.createUser=/api/createAccount
endpoint.updateUser=/api/updateAccount
endpoint.deleteUser=/api/deleteAccount

# Test Data
search.product=top
user.name=Madhavi
user.password=12345
user.title=Mrs
user.firstname=Sai
user.lastname=Madhavi
user.company=TestCompany
user.address1=Hyderabad
user.address2=India
user.country=India
user.zipcode=500001
user.state=Telangana
user.city=Hyderabad
user.mobile=9999999999

# Invalid Credentials
invalid.username=wrong@gmail.com
invalid.password=wrong123

# URLs
login.url=/login
products.url=/products

# Timeouts
connection.timeout=5000
read.timeout=5000